// Purpose: Parse clauses/artifacts, retrieve candidates, build matrices and calculate exact impact.
import{createHash}from'node:crypto';const hash=x=>createHash('sha256').update(x).digest('hex'),tokens=x=>new Set(x.toLowerCase().match(/[a-z0-9_]+/g)??[]);
export function parseMarkdown(text){const out=[];let parent='';for(const line of text.split('\n')){const h=line.match(/^#{1,6}\s+((?:\d+\.)*\d+)\s+(.+)/);if(h){parent=h[1];out.push({id:h[1],text:h[2],hash:hash(h[2])});continue}const li=line.match(/^\s*[-*]\s+(.+)/);if(li){const id=`${parent||'item'}.${out.filter(x=>x.id.startsWith(parent||'item')).length+1}`;out.push({id,text:li[1],hash:hash(li[1])})}}return out}
export function parseCsv(text){const[l,...rows]=text.trim().split(/\r?\n/);const h=l.split(',');return rows.map(r=>{const v=r.split(',');const id=v[h.indexOf('clause_id')],body=v[h.indexOf('text')];return{id,text:body,hash:hash(body)}})}
export function splitArtifact(path,text){const ext=path.split('.').pop();let parts;if(['js','mjs','c','java'].includes(ext))parts=text.split(/(?<=\})\s*(?=(?:export\s+)?(?:function|class|const)\b)/);else if(['py','rb'].includes(ext))parts=text.split(/(?=^(?:def|class)\s)/m);else parts=text.split(/\n\s*\n/);return parts.filter(Boolean).map((body,i)=>({id:`${path}:${i+1}`,path,text:body,kind:/test|spec/.test(path)?'test':'source',hash:hash(body)}))}
export function retrieve(clause,artifacts,limit=5,hints={}){return artifacts.map(a=>{const overlap=[...tokens(clause.text)].filter(x=>tokens(a.text).has(x)).length;const hint=(hints[clause.id]??[]).some(x=>a.path.includes(x))?10:0;return{artifact:a,score:overlap+hint}}).sort((a,b)=>b.score-a.score||a.artifact.id.localeCompare(b.artifact.id)).slice(0,limit).map(x=>x.artifact)}
export function questions(artifact){return artifact.kind==='test'?[{id:'implements',statement:'Does this artifact implement the clause?'},{id:'verifies',statement:'Does this test verify the clause?'}]:[{id:'implements',statement:'Does this artifact implement the clause?'}]}
export function matrix(clauses,artifacts,matches,threshold=.5){const accepted=matches.filter(x=>x.probability>=threshold);const covered=new Set(accepted.map(x=>x.clauseId)),used=new Set(accepted.map(x=>x.artifactId));return{cells:matches,coverage:covered.size/clauses.length,uncovered:clauses.filter(x=>!covered.has(x.id)).map(x=>x.id),orphans:artifacts.filter(x=>!used.has(x.id)).map(x=>x.id)}}
export function impact(previous,{clauses=[],artifacts=[]}){const changed=new Set([...clauses.map(x=>x.id),...artifacts.map(x=>x.id)]);return previous.cells.filter(x=>changed.has(x.clauseId)||changed.has(x.artifactId))}
export function check(previous,current){return{ok:current.coverage>=previous.coverage&&!previous.cells.some(p=>p.probability>=.5&&!current.cells.some(c=>c.clauseId===p.clauseId&&c.artifactId===p.artifactId&&c.probability>=.5)),coverageDropped:current.coverage<previous.coverage}}
export function htmlReport(data){return`<!doctype html><meta charset=utf-8><title>Trace matrix</title><style>body{font:16px system-ui;max-width:80rem;margin:auto}</style><h1>Trace matrix</h1><pre>${JSON.stringify(data,null,2).replaceAll('&','&amp;').replaceAll('<','&lt;')}</pre>`}
